export const GLOBAL_LEADERBOARD = {
  DEFAULT_START_DATE: process.env.NEXT_PUBLIC_DEFAULT_GLOBAL_LEADERBOARD_START_DATE as string,
  DEFAULT_END_DATE: process.env.NEXT_PUBLIC_DEFAULT_GLOBAL_LEADERBOARD_END_DATE as string,
};
