export const GLOBAL_LEADERBOARD = {
  START_DATE: process.env.NEXT_PUBLIC_GLOBAL_LEADERBOARD_START_DATE as string,
  END_DATE: process.env.NEXT_PUBLIC_GLOBAL_LEADERBOARD_END_DATE as string,
  CUT_OFF: process.env.NEXT_PUBLIC_GLOBAL_LEADERBOARD_CUT_OFF as string,
  ANNOUNCEMENT_DATE: process.env.NEXT_PUBLIC_GLOBAL_LEADERBOARD_WINNER_ANNOUNCEMENT_DATE as string,
  ANNOUNCEMENT_PLACE: process.env
    .NEXT_PUBLIC_GLOBAL_LEADERBOARD_WINNER_ANNOUNCEMENT_PLACE as string,
  IS_FOR_EVENT: process.env.NEXT_PUBLIC_GLOBAL_LEADERBOARD_IS_FOR_EVENT === 'ON',
};
