pipeline {
    agent {
        docker {
            image 'node:8.12.0' 
        }
    }
    environment {
        HOME = '.'
    }
    stages {
        stage('PreInstall') {
          steps {
            sh 'npm install -g pnpm'
          }
        }

        stage('Build') { 
            steps {
                sh 'pnpm install' 
            }
        }
    }
}