pipeline {
    agent {
        docker {
            image 'node:lts-bullseye-slim' 
            args '-p 3000:3000' 
        }
    }
    stages {
        stage('PreInstall') {
          steps {
            sh 'wget -qO- https://get.pnpm.io/install.sh | sh -'
          }
        }

        stage('Build') { 
            steps {
                sh 'pnpm install' 
            }
        }
    }
}